### ISSUE TITLE
RxAutoComplete does not show up in design view

### ISSUE THREAD

**Issue by webdevotion** [dima/restfulx_framework#10]
RxAutoComplete does not show up in design view when using Flex Builder. Can be confusing when designers are collaborating on the project.

**Comment by dima** [comment]
FlexBuilder sucks, what can I say? :) Want to take a stab at it? I've no idea, why it's not showing up, but I do agree it's a bit annoying.

**Comment by webdevotion** [comment]
Is that an order? : )
Will keep it mind!

**Comment by dima** [comment]
WONTFIX
