### ISSUE TITLE
Unmeaningful error when model is not registered with RxApplicationController

### ISSUE THREAD

**Issue by ximus** [dima/restfulx_framework#13]
This is an Enhancement.

When you forget to register a model in your app controller (RxApplicationController), you get the following error during unmarshelling of an entity that references it:

```
<current object> not not been unmarshalled. Error: TypeError: Error #1009: Cannot access a    property or method of a null object reference.
```

(thrown from line 89 in XMLSerializer.as)

It would be nice, although not necessary to have a more meaningful error.

Yell at me if I'm wasting your time, I'm new to the software dev. world.
Max

**Comment by dima** [comment]
No further requirements on this.
