### ISSUE TITLE
uuidtools 2.0.0 compatibilty

### ISSUE THREAD

**Issue by ximus** [dima/restfulx_framework#15]
Hello,

I put together a simple Air app backed by a Rails server and glued with Resfulx.

Today I tried to run it with uuidtools 2.0.0 and got this:

```
undefined method 'random_create' for UUID:Class (something like that)
```

I did the following to fix it:

Modified **line 14** in <gems_path>/restfulx-1.2.2/lib/restfulx/**active_record_uuid_helper.rb**:

from: `self.id = UUID.random_create.to_s.gsub("-", "") unless self.id`
to: `self.id = UUIDTools::UUID.random_create.to_s.gsub("-", "") unless self.id`

The UUID class is inside the UUIDTools module in the uuidtools gem (version 2.0.0). 

There is a UUID class outside the UUIDTools module but it only keeps track of the gem's version (MAJOR, MINOR, etc). I checked and this is a changle from uuidtools 1.x.x.

**Comment by dima** [comment]
thanks! I'll patch ASAP.

**Comment by dima** [comment]
fixed.
