### ISSUE TITLE
Revision format changed in CouchDB 0.9

### ISSUE THREAD

**Issue by aschoeller** [dima/restfulx_framework#16]
I tried the example from the wiki http://wiki.github.com/dima/restfulx_framework/working-with-restfulx-service-providers using CouchDB as primary and AIR-ServiceProvider as secondary storage. Writing to the AIR-storage failed on any model. Cause it's impossible to convert the _rev-Attribute to a  AS3-Number-type. In couchDB 0.9 a revision is made of a Integer +"-"+ Integer(timestamp/ticks) eg. "3-1514039775". AIRServiceProvider.as tries to convert to a Number and fails silently. I changed the SQL-filed-type in line 496 from "INTEGER" to "TEXT" - i'm not sure if this will show undesired consequences elsewhere ? I've seen none so far.
greets andreas

**Comment by dima** [comment]
Fixed
