### ISSUE TITLE
nested attributes and '_delete'

### ISSUE THREAD

**Issue by fd** [dima/restfulx_framework#17]
On [this line](http://github.com/dima/restfulx_framework/blob/cd50eaea585e297b7678f37a19f8497fa6e83696/framework/src/org/restfulx/services/http/XMLHTTPServiceProvider.as#L502) "delete" is used instead of  the rails default "_delete" ( [see here](http://apidock.com/rails/ActiveRecord/NestedAttributes/ClassMethods/accepts_nested_attributes_for) ).

**Comment by dima** [comment]
Closed by 1db7fc046ce62203830f222cea2777499c41b9f0 and adds a flag to always do a show on a model in
RxAutoComplete

**Comment by fd** [comment]
cool thanks!
