### ISSUE TITLE
HABTM issue with _ids

### ISSUE THREAD

**Issue by webdevotion** [dima/restfulx_framework#18]
Trying to save / destroy lines that belong to a brand ( and vice versa ) using _ids.  But things don't work out.

From the processing log of my BrandsController:

"line_ids"=>"2,1,3" // only updates the first index, rest is ignored

// the rails way does not work either from my flex app

// as seen in railscast #17 http://railscasts.com/episodes/17

// I know there are quotes in my code

"line_ids"=>"['2','1','3']" 

// when override the uncast method in RxUtils I get the following

// but _attributes don't work with HABTM

"line_ids_attributes"=>["3", "1", "2"]

Processing BrandsController#update to fxml (for 127.0.0.1 at 2009-08-12 02:22:02) [PUT]
  Parameters: {"brand"=>{"name"=>"Mercedes", "created_at"=>"2009-08-07T10:00:45-00:00", "updated_at"=>"2009-08-07T10:00:45-00:00", "line_ids"=>"2,1,3"}, "format"=>"fxml", "action"=>"update", "_method"=>"PUT", "id"=>"2", "controller"=>"brands"}

// script/console output:

b = Brand.find(:first)
=> #<Brand id: 1, name: "BMW", created_at: "2009-08-07 10:00:45", updated_at: "2009-08-07 10:00:45">

> > b.line_ids = [1,2,3]
> > => [1, 2, 3]

**Comment by dima** [comment]
HABTM is not supported (and very unlikely to be supported due to it's un-RESTful nature).

**Comment by webdevotion** [comment]
fair enough ;)
