### ISSUE TITLE
JSONSerializer can't unmarshall objects that have underscores in their names

### ISSUE THREAD

**Issue by bruz** [dima/restfulx_framework#19]
The problem is described here:

http://groups.google.com/group/restfulx-framework/browse_thread/thread/9e3c43488df1d6b0/425fa9bb9d960268?hl=en&ie=UTF-8&oe=utf-8&q=restfulx+json#425fa9bb9d960268

What's happening is that JSONSerializer is giving VOSerializer the model name using underscores, when it needs it in CamelCase. I've made a fix in my fork of restfulx_framework that fixes this:

http://github.com/bruz/restfulx_framework/commit/c2fb4ce993ca78c1e91fb2299442f001384e6b74

**Comment by dima** [comment]
Fixed as per the commit details
