### ISSUE TITLE
RxAutoComplete should have the option to always hit the server

### ISSUE THREAD

**Issue by elvisfernandes** [dima/restfulx_framework#22]
Depending on the models you have on your database, a first call to the server by RxAutoComplete could fetch some models (but not all) that suits a later request, avoiding RxAutoComplete to load all the suitable models for later requests.

A solution for this could be to create a property, say, useCache, to flag that RxAutoComplete should always try to hit the server.

**Comment by dima** [comment]
RxAutoComplete refactoring (adding manualSearch option) should solve this.
