### ISSUE TITLE
NIL error in rake task db:schema:to_yaml

### ISSUE THREAD

**Issue by ghost** [dima/restfulx_framework#23]
Hi,

I'm getting a NIL error while running $rake db:schema:to_yaml
using the db/schema.rb from a standard Spree application (www.spreecommerce.com).
I use restfulx 1.2.4

I correct this on my machine in /usr/lib/ruby/gems/1.8/gems/restfulx-1.2.4/lib/restfulx/rails/schema_to_yaml.rb

line 87 :         last_in_array_fix = last_in_array_fix.gsub(', ','') if not(last_in_array_fix.nil?)
...
line 96 :        last_in_array_fix = last_in_array_fix.gsub(', ','') if not(last_in_array_fix.nil?)

Regards,

Bruno.

**Comment by dima** [comment]
Hi Bruno,

This should already be fixed in trunk.

**Comment by dima** [comment]
Fixed
