### ISSUE TITLE
sqlite schema

### ISSUE THREAD

**Issue by istrasci** [dima/restfulx_framework#37]
Would be nice if every time an AIR application ran, RestfulX would update the sqlite schema based on the current models' properties.  I often add a column to the server side model, and then add the corresponding property to my AS model, but forget to update the sqlite schema to reflect this.  Or sometimes remove a column that's no longer necessary.  Or even change a column's type.

For example, I have an AIR application that is used by multiple clients.  It has an auto-update feature, so the clients can always stay up-to-date.  However, as it currently stands, they have to wipe out their sqlite file whenever there is a change to the server DB schema.  This is not feasible, especially when they have already used the application to save lots of data.

**Comment by dima** [comment]
Adding ability to migrate SQLite tables in AIR when models change.
Closed by 1a090bb07a8eb0073ef5fe4b9c2a46b3ed4de0d9
