### ISSUE TITLE
PushStartEvent

### ISSUE THREAD

**Issue by istrasci** [dima/restfulx_framework#50]
I feel like I entered this ticket before, but maybe not.  It seems that the _PushStartEvent_ is dispatched for every dirty model during a push.  This seems counter-intuitive, and that it should really only be dispatched once (as _PullStartEvent_ is).

**Comment by dima** [comment]
Thanks for the report. I'll double check issue and get it fixed for 1.3.1

**Comment by dima** [comment]
Closed by 6b6e98aaeb7afe6ddb40d8b6a0d75fffad20524b
